using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace MidiPlayerTK
{
    /// <summary>
    /// [MPTK PRO] List of ranges available
    /// </summary>
    public enum MPTKRangeName
    {
        MajorMelodic = 0,
        MajorHarmonic = 1,
        MinorNatural = 2,
        MinorMelodic = 3,
        MinorHarmonic = 4,
        PentatonicMajor = 5,
        PentatonicMinor = 6,
        Chromatic = 7,
        Blues = 8,
        Enigmatic1 = 9,
        Enigmatic2 = 10,
        Gitane = 11,
        Oriental1 = 12,
        BebopMajor = 13,
        AeolienB5 = 14,
        Arabic = 15,
        Augmented = 16,
        Bahar = 17,
        Balinaise = 18,
        Bartock = 19,
        BebopDominante = 20,
        Aeolien = 21,
        BebopMinor = 22,
        BitonalMajorChromatic = 23,
        BitonalMinorChromatic = 24,
        BluesDecreased1 = 25,
        BluesDecreased2 = 26,
        MajorBlues1 = 27,
        MinorBlues1 = 28,
        MajorBlues2 = 29,
        MinorBlues2 = 30,
        Chinese1 = 31,
        Chinese2 = 32,
        DemiDecreased = 33,
        DemiTonNoSixte = 34,
        Diminish = 35,
        Dorien = 36,
        Spanish1 = 37,
        Spanish2 = 38,
        Spanish8 = 39,
        Gypsy = 40,
        Hexalydien = 41,
        HexaMelodic = 42,
        HexaPhrygien = 43,
        HexaTritoniqueBinary = 44,
        HexaTritoniqueDecreased1 = 45,
        HexaTritoniqueDecreased2 = 46,
        HexaTritoniqueDecreased3 = 47,
        Hindou = 48,
        Hirajoshi = 49,
        HongroiseGitane = 50,
        HongroiseMajor = 51,
        HongroiseMinor = 52,
        Indoustane = 53,
        Ionien = 54,
        Ionien5 = 55,
        Iwato = 56,
        Javanais = 57,
        KokinJoshi = 58,
        Kumoi = 59,
        Locrien = 60,
        Locrien6 = 61,
        Lydien1 = 62,
        Lydien2 = 63,
        Lydien3 = 64,
        Mixolydien = 65,
        NapolitanMajor = 66,
        NapolitanMinor = 67,
        Oriental2 = 68,
        Oriental3 = 69,
        PentatonicHarmonic = 70,
        PentatonicDominante = 71,
        PentatonicEgyptian = 72,
        PentatonicJapanese = 73,
        PentatonicLocrien1 = 74,
        PentatonicLocrien2 = 75,
        PentatonicMauritanian = 76,
        PentatonicPelog = 77,
        Persane1 = 78,
        Persane2 = 79,
        Phrygien = 80,
        Promethee = 81,
        RoumanMinor = 82,
        SuperlocrienBB7 = 83,
        SuperlocrienAltered = 84,
        TonByTon = 85,
    }
}
